singleuser:
  defaultUrl: "/lab?welcome"
  image:
    name: 525978535215.dkr.ecr.us-west-1.amazonaws.com/citywide-jupyterlab
    tag: e3cf7bbaf580
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
